title: 喜欢你，没道理                     #你博客的标题
SEOTitle: 你的博客 | You Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/1.jpg     #显示在首页的背景图片   
keyword: "zwe7616175" #关键词
url: "https://zwe7616175.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
